const translations = {
    en: {
        brand: "Mohor",
        cart: "Cart",
        shop: "Shop",
        facebook: "Facebook",
        instagram: "Instagram",
        collection: "Our Collection",
        filters: "Filters",
        sort_default: "Sort by: Default",
        sort_low_high: "Price: Low to High",
        sort_high_low: "Price: High to Low",
        cat_title: "Categories",
        price_title: "Price",
        empty_cart: "Your cart is empty.",
        total: "Total:",
        checkout: "Order via WhatsApp",
        desc: "Description",
        details: "Product Details",
        add_to_cart: "Add to Cart",
        footer: "© 2026 Mohor Clothings Bangladesh. All Rights Reserved."
    },
    bn: {
        brand: "মোহর",
        cart: "কার্ট",
        shop: "শপ",
        facebook: "ফেসবুক",
        instagram: "ইনস্টাগ্রাম",
        collection: "আমাদের কালেকশন",
        filters: "ফিল্টার",
        sort_default: "সাজান: ডিফল্ট",
        sort_low_high: "দাম: কম থেকে বেশি",
        sort_high_low: "দাম: বেশি থেকে কম",
        cat_title: "ক্যাটাগরি",
        price_title: "দাম",
        empty_cart: "আপনার কার্ট খালি।",
        total: "মোট:",
        checkout: "হোয়াটসঅ্যাপে অর্ডার করুন",
        desc: "বিবরণ",
        details: "পণ্যের বিবরণ",
        add_to_cart: "কার্টে যোগ করুন",
        footer: "© ২০২৬ মোহর ক্লথিংস বাংলাদেশ। সর্বস্বত্ব সংরক্ষিত।"
    }
};
